### PR TITLE
fix debian build error due to missing depends

### PR DESCRIPTION
**Pull request by hsbasu**
- Add libgtk-3-dev, pkg-config, cmake and systemd as build dependencies

### CODE REVIEW

**Comment by mtwebster** [comment]
Hi, I just removed gtk completely, as we don't use it anywhere.

Also, the cmake thing isn't really an issue.  When meson has multiple tools it uses to find a dependency, one of its fallbacks is cmake, but 99% of the time the pkg-config failure is the real problem, and has nothing to do with cmake. Check out https://mesonbuild.com/Dependencies.html#dependency-detection-method.

**Comment by hsbasu** [comment]
Hi @mtwebster I tried building the package using `pbuilder` after your commit. I am still getting the error. Can you please check out the following log from `pbuilder`

```
I: Building the package
I: Running cd /build/xdg-desktop-portal-xapp-1.0.2/ && env PATH="/usr/sbin:/usr/bin:/sbin:/bin" HOME="/nonexistent" dpkg-buildpackage -us -uc  && env PATH="/usr/sbin:/usr/bin:/sbin:/bin" HOME="/nonexistent" dpkg-genchanges -S  > ../xdg-desktop-portal-xapp_1.0.2_source.changes
dpkg-buildpackage: info: source package xdg-desktop-portal-xapp
dpkg-buildpackage: info: source version 1.0.2
dpkg-buildpackage: info: source distribution victoria
dpkg-buildpackage: info: source changed by Clement Lefebvre <root@linuxmint.com>
 dpkg-source --before-build .
dpkg-buildpackage: info: host architecture amd64
 fakeroot debian/rules clean
dh clean
   dh_clean
 dpkg-source -b .
dpkg-source: info: using source format '3.0 (native)'
dpkg-source: info: building xdg-desktop-portal-xapp in xdg-desktop-portal-xapp_1.0.2.tar.xz
dpkg-source: info: building xdg-desktop-portal-xapp in xdg-desktop-portal-xapp_1.0.2.dsc
 debian/rules build
dh build
   dh_update_autotools_config
   dh_autoreconf
   dh_auto_configure
	cd obj-x86_64-linux-gnu && LC_ALL=C.UTF-8 meson .. --wrap-mode=nodownload --buildtype=plain --prefix=/usr --sysconfdir=/etc --localstatedir=/var --libdir=lib/x86_64-linux-gnu
The Meson build system
Version: 0.61.2
Source dir: /build/xdg-desktop-portal-xapp-1.0.2
Build dir: /build/xdg-desktop-portal-xapp-1.0.2/obj-x86_64-linux-gnu
Build type: native build
Project name: xdg-desktop-portal-xapp
Project version: 1.0.2
C compiler for the host machine: cc (gcc 11.3.0 "cc (Ubuntu 11.3.0-1ubuntu1~22.04.1) 11.3.0")
C linker for the host machine: cc ld.bfd 2.38
Host machine cpu family: x86_64
Host machine cpu: x86_64
Found pkg-config: /usr/bin/pkg-config (0.29.2)
Did not find CMake 'cmake'
Found CMake: NO
Run-time dependency systemd found: NO (tried pkgconfig)

../meson.build:16:2: ERROR: Dependency "systemd" not found, tried pkgconfig

A full log can be found at /build/xdg-desktop-portal-xapp-1.0.2/obj-x86_64-linux-gnu/meson-logs/meson-log.txt
	cd obj-x86_64-linux-gnu && tail -v -n \+0 meson-logs/meson-log.txt
==> meson-logs/meson-log.txt <==
Build started at 2023-06-29T14:20:57.846862
Main binary: /usr/bin/python3
Build Options: -Dprefix=/usr -Dlibdir=lib/x86_64-linux-gnu -Dlocalstatedir=/var -Dsysconfdir=/etc -Dbuildtype=plain -Dwrap_mode=nodownload
Python system: Linux
The Meson build system
Version: 0.61.2
Source dir: /build/xdg-desktop-portal-xapp-1.0.2
Build dir: /build/xdg-desktop-portal-xapp-1.0.2/obj-x86_64-linux-gnu
Build type: native build
Project name: xdg-desktop-portal-xapp
Project version: 1.0.2
Sanity testing C compiler: cc
Is cross compiler: False.
Sanity check compiler command line: cc sanitycheckc.c -o sanitycheckc.exe -g -O2 -ffile-prefix-map=/build/xdg-desktop-portal-xapp-1.0.2=. -flto=auto -ffat-lto-objects -flto=auto -ffat-lto-objects -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -D_FILE_OFFSET_BITS=64 -Wl,-Bsymbolic-functions -Wl,-z,relro -Wl,-z,now
Sanity check compile stdout:

-----
Sanity check compile stderr:

-----
Running test binary command: /build/xdg-desktop-portal-xapp-1.0.2/obj-x86_64-linux-gnu/meson-private/sanitycheckc.exe
C compiler for the host machine: cc (gcc 11.3.0 "cc (Ubuntu 11.3.0-1ubuntu1~22.04.1) 11.3.0")
C linker for the host machine: cc ld.bfd 2.38
Sanity testing C compiler: cc
Is cross compiler: False.
Sanity check compiler command line: cc sanitycheckc.c -o sanitycheckc.exe -g -O2 -ffile-prefix-map=/build/xdg-desktop-portal-xapp-1.0.2=. -flto=auto -ffat-lto-objects -flto=auto -ffat-lto-objects -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -D_FILE_OFFSET_BITS=64 -Wl,-Bsymbolic-functions -Wl,-z,relro -Wl,-z,now
Sanity check compile stdout:

-----
Sanity check compile stderr:

-----
Running test binary command: /build/xdg-desktop-portal-xapp-1.0.2/obj-x86_64-linux-gnu/meson-private/sanitycheckc.exe
C compiler for the build machine: cc (gcc 11.3.0 "cc (Ubuntu 11.3.0-1ubuntu1~22.04.1) 11.3.0")
C linker for the build machine: cc ld.bfd 2.38
Build machine cpu family: x86_64
Build machine cpu: x86_64
Host machine cpu family: x86_64
Host machine cpu: x86_64
Target machine cpu family: x86_64
Target machine cpu: x86_64
Pkg-config binary for 1 is not cached.
Pkg-config binary missing from cross or native file, or env var undefined.
Trying a default Pkg-config fallback at pkg-config
Found pkg-config: /usr/bin/pkg-config (0.29.2)
Determining dependency 'systemd' with pkg-config executable '/usr/bin/pkg-config'
env[PKG_CONFIG_PATH]: 
Called `/usr/bin/pkg-config --modversion systemd` -> 1

CMake binary for 1 is not cached
CMake binary missing from cross or native file, or env var undefined.
Trying a default CMake fallback at cmake
Did not find CMake 'cmake'
Found CMake: NO
CMake binary for machine 1 not found. Giving up.
Run-time dependency systemd found: NO (tried pkgconfig)

../meson.build:16:2: ERROR: Dependency "systemd" not found, tried pkgconfig
dh_auto_configure: error: cd obj-x86_64-linux-gnu && LC_ALL=C.UTF-8 meson .. --wrap-mode=nodownload --buildtype=plain --prefix=/usr --sysconfdir=/etc --localstatedir=/var --libdir=lib/x86_64-linux-gnu returned exit code 1
make: *** [debian/rules:6: build] Error 25
dpkg-buildpackage: error: debian/rules build subprocess returned exit status 2
```

**NB:** I won't be able to build the package on Launchpad unless a clean-build using `pbuilder` succeeds.

**Comment by mtwebster** [comment]
Does adding 'systemd' to build-deps work? If so I'll add it, that has the pkgconfig file with `systemduserunitdir` defined.

**Comment by hsbasu** [comment]
> Does adding 'systemd' to build-deps work? If so I'll add it, that has the pkgconfig file with `systemduserunitdir` defined.

@mtwebster You were right. Systemd was the only build dependency that was needed. I have updated the PR. Can you please reopen it?

**Comment by hsbasu** [comment]
Sorry I did not see your commit on adding systemd. I have modified the PR fixing a lintian error. So it still can be merged.

**Comment by mtwebster** [comment]
I already added systemd yesterday - https://github.com/linuxmint/xdg-desktop-portal-xapp/commit/a090b253cadb4768fbcc65fa49aeb5743d2bd408

We don't need pkg-config as a dependency as it's already a dependency of a couple of our other deps - it's typically only depended on by library dev packages for the .pc file location.

The cmake thing I explained about how meson works, we don't need that either.

**Comment by hsbasu** [comment]
@mtwebster I removed all the dependencies from the PR. The only change this PR contain is a missing comma(,). So can you please reopen it?

**Comment by mtwebster** [comment]
I'm not sure where you're looking, this PR still shows:

image

**Comment by hsbasu** [comment]
This is from my branch.
git

**Pull request closed without merging**
